### ISSUE TITLE
suggestion: use a lower timeout for the debouncing of the search queries

### ISSUE THREAD

**Issue by Haroenv** [listcommunity/support#1]
Hey! I know that you're on a community plan and thus have a limited amount of queries per second, but it would be a lot better for UI if the debouncing was less than 1000ms. Do you think you could try a lower number?

**Comment by dmfrancisco** [comment]
Thanks, this should be fixed now 👍

**Comment by Haroenv** [comment]
Still a denounce but less noticeable than before :+1:
